scripts: Fix implicit declaration warnings in fips_crypto_utils
Fixed several implicit declaration warnings in `fips_crypto_utils.c` by including the required headers.

Warnings resolved:
- Implicit declaration of `strcmp` by adding `#include <string.h>`.
- Implicit declaration of `update_crypto_hmac` and `collect_crypto_bytes` by ensuring their declarations are available in the file.

This resolves the following warnings:
../scripts/fips_crypto_utils.c:28:14: warning: implicit declaration of function ‘strcmp’
../scripts/fips_crypto_utils.c:52:24: warning: implicit declaration of function ‘update_crypto_hmac’
../scripts/fips_crypto_utils.c:82:24: warning: implicit declaration of function ‘collect_crypto_bytes’

Original reference: https://github.com/TheGalaxyProject/tgpkernel-s7-o/commit/8dafdc8769f37116a94a392483517361dfcf4d38

Signed-off-by: Robin <hanya8493@gmail.com>